max_depths: 
#  - 2
#  - 5
#  - 10
#  - 12
#  - 14
#  - 16
#  - 18
#  - 20
#  - 22
#  - 24
#  - 26
#  - 28
 - 30
#  - 35
#  - 40
#  - 50
min_samples_leaves: 
#  - 1
 - 2
#  - 3
#  - 4
#  - 5
#  - 6
#  - 7
#  - 8
#  - 9
#  - 10
#  - 11
#  - 12
#  - 13
#  - 14
#  - 15
ccp_alphas:
#  - 0.0
 - 0.00005
#  - 0.0001
 - 0.0002
 - 0.0003
 - 0.0004
 - 0.0005
#  - 0.001
#  - 0.002
#  - 0.005
#  - 0.01
#  - 0.015
#  - 0.02
#  - 0.03
#  - 0.05
#  - 0.075
#  - 0.1
#  - 0.15
#  - 0.2
criterions:
 - "gini"
dataset: "pcb"
# dataset: "wine"
# dataset: "iris"
n_splits: 5
rep_count: 10
